#acceptance-tests:
#  build: build/docker
#  links:
#    - zookeeper:zk
#    - query
#  environment:
#    spring.cloud.zookeeper.connectString: zk:2181
#    spring.zipkin.enabled: 'false'
#    spring.zipkin.query.url: query
#    TERM: dumb
#  command: ./gradlew clean --version --no-daemon
#  dns:
#    - 8.8.8.8
#    - 8.8.4.4

aggregating:
  build: aggregating/build/docker
  links:
    - zookeeper:zk
    - collector:ck
  environment:
      spring.zipkin.host: ck
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9992:9992

maturing:
  build: maturing/build/docker
  links:
    - zookeeper:zk
    - collector:ck
  environment:
      spring.zipkin.host: ck
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9993:9993

bottling:
  build: bottling/build/docker
  links:
    - zookeeper:zk
    - collector:ck
  environment:
      spring.zipkin.host: ck
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9994:9994

presenting:
  build: presenting/build/docker
  links:
    - zookeeper:zk
    - collector:ck
  environment:
      spring.zipkin.host: ck
  command: --spring.cloud.zookeeper.connectString=zk:2181
  ports:
    - 9991:9991

zookeeper:
  image: jplock/zookeeper
  expose:
    - 2181

mysql:
  image: openzipkin/zipkin-mysql:1.25.0
  ports:
    - 3306:3306

collector:
  image: openzipkin/zipkin-collector:1.25.0
  environment:
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=mysql
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - mysql:storage

query:
  image: openzipkin/zipkin-query:1.25.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage

web:
  image: openzipkin/zipkin-web:1.25.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query
